demo47 demo48 demo60 demo61 : demo47.cpp demo48.cpp demo60.cpp demo61.cpp
	g++ -g -o demo47 demo47.cpp ../_freecplus.cpp
	g++ -g -o demo48 demo48.cpp ../_freecplus.cpp
	g++ -g -o demo60 demo60.cpp ../_freecplus.cpp
	g++ -g -o demo61 demo61.cpp ../_freecplus.cpp
      

